config/routes.rb
ExampleStore::Application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/shoppe"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
  
  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_filter(:except => :status) { redirect_to root_path unless has_order? }
  
  def status
    @order = Shoppe::Order.find_by_token!(params[:token])
  end
  
  def destroy
    current_order.destroy
    session[:order_id] = nil
    respond_to do |wants|
      wants.html { redirect_to root_path, :notice => "Your basket has been emptied successfully."}
      wants.json do
        flash[:notice] = "Your shopping bag is now empty."
        render :json => {:status => 'complete', :redirect => root_path}
      end
    end
  end
  
  def remove_item
    item = current_order.order_items.find(params[:order_item_id])
    if current_order.order_items.count == 1
      destroy
    else
      item.remove
      respond_to do |wants|
        wants.html { redirect_to request.referer, :notice => "Item has been removed from your basket successfully"}
        wants.json do
          current_order.reload
          render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
        end
      end
    end
  end
  
  def change_item_quantity
    item = current_order.order_items.find(params[:order_item_id])
    request.delete? ? item.decrease! : item.increase!
    respond_to do |wants|
      wants.html { redirect_to request.referer || root_path, :notice => "Quantity has been updated successfully." }
      wants.json do
        current_order.reload
        if current_order.empty?
          destroy
        else
          render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
        end
      end
    end    
  rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "Unfortunately, we don't have enough stock. We only have #{e.available_stock} items available at the moment. Please get in touch though, we're always receiving new stock." }
      wants.json { render :json => {:status => 'error', :message => "Unfortunateley, we don't have enough stock to add more items."} }
    end
  end

  def change_delivery_service
    if current_order.delivery_service = current_order.available_delivery_services.select { |s| s.id == params[:delivery_service].to_i}.first
      current_order.save
      respond_to do |wants|
        wants.html { redirect_to request.referer, :notice => "Delivery service has been changed"}
        wants.json do
          current_order.reload
          render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
        end
      end
    else
      respond_to do |wants|
        wants.html { redirect_to request.referer, :alert => "You cannot select this delivery method."}
        wants.json { render :json => {:status => 'error', :message => 'InvalidDeliveryMethod'}, :status => 422 }
      end
    end
  end
  
  def checkout
    @order = Shoppe::Order.find(current_order.id)
    
    
    if request.patch?
      @order.attributes = params[:order].permit(:first_name, :last_name, :company, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number, :delivery_name, :delivery_address1, :delivery_address2, :delivery_address3, :delivery_address4, :delivery_postcode, :delivery_country_id, :separate_delivery_address)
      @order.ip_address = request.ip
      if @order.proceed_to_confirm
        redirect_to checkout_confirmation_path
      end
    else
      # Add some example order data for the example. In a real application
      # this shouldn't be present.
      Faker::Config.locale = 'en-gb'
      @order.first_name = "arun"                                            if @order.first_name.blank?
      @order.last_name = "chavan"                                              if @order.last_name.blank?
      @order.company = "flipkart"                                                  if @order.company.blank?
      @order.email_address = "fish@example.com"                                          if @order.email_address.blank?
      @order.phone_number = "919191919191"                                if @order.phone_number.blank?
      @order.billing_address1 = "2 nd cross" + " " + " KR road"   if @order.billing_address1.blank?
      @order.billing_address3 = "Bangalore"                                                 if @order.billing_address3.blank?
      @order.billing_address4 = "India"                                             if @order.billing_address4.blank?
      @order.billing_postcode = "571301"                                                 if @order.billing_postcode.blank?
    end
  end
  
  def payment
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      redirect_to checkout_confirmation_path
    end
  end
  
  def confirmation
    unless current_order.confirming?
      redirect_to checkout_path
      return
    end
    
    if request.patch?
      begin
        current_order.confirm!
        # This payment method should usually be called in a payment module or elsewhere but for the demo
        # we are adding a payment to the order straight away.
        current_order.payments.create(:method => "Credit Card", :amount => current_order.total, :reference => rand(10000) + 10000, :refundable => true)
        session[:order_id] = nil
        redirect_to root_path, :notice => "Order has been placed!"
      rescue Shoppe::Errors::PaymentDeclined => e
        flash[:alert] = "Payment was declined by the bank. #{e.message}"
        redirect_to checkout_path
      rescue Shoppe::Errors::InsufficientStockToFulfil
        flash[:alert] = "We're terribly sorry but while you were checking out we ran out of stock of some of the items in your basket. Your basket has been updated with the maximum we can currently supply. If you wish to continue just use the button below."
        redirect_to checkout_path
      end
    end
  end
    
end

app/views/orders/_checkout_sidebar.html.haml
= content_for :sidebar do
  .checkout
    %dl
      %dt Are my card details safe?
      %dd Yes! This site is hosted using industry-standard encryption & we don't store your card details on our servers.
      %dt How long will my order take to arrive?
      %dd This will depend on what delivery method you select opposite. If ordered before 4pm, all orders are despatched the same day.
      %dt What payment methods do you accept?
      %dd We accept Visa, Mastercard & American Express credit/debit cards.

app/views/orders/checkout.html.haml
- @page_title = 'Checkout'
= render 'checkout_sidebar'
    
.checkout
  %p.secure Secure connection
  %h2 Place your order
  %p.intro
    Fantastic! You're ready to place your order, just follow the instructions below and
    we'll get your products shipped to you as quickly as we can.

  %h3 Review the products in your shopping bag
  = render 'shared/order_items', :order => @order

  - unless false && @order.delivery_service.nil?
    %h3 Complete your details below to complete your order
    
    = form_for @order, :url => checkout_path, :html => {:class => 'checkout disableable'} do |f|
      = f.error_messages
      .customer
        = field_set_tag do
          %dl
            %dt= f.label :first_name, "Name", :class => 'req'
            %dd.name
              = f.text_field :first_name, :placeholder => 'First Name'
              = f.text_field :last_name, :placeholder => 'Last Name'
          %dl
            %dt= f.label :company, "Company Name (optional)"
            %dd= f.text_field :company
          %dl
            %dt= f.label :email_address, 'Your E-Mail Address', :class => 'req'
            %dd= f.text_field :email_address
          %dl
            %dt= f.label :phone_number, 'Your Contact Phone Number', :class => 'req'
            %dd= f.text_field :phone_number

        = field_set_tag do
          %dl
            %dt= f.label :billing_address1, "Billing Address", :class => 'req'
            %dd= f.text_field :billing_address1, :placeholder => "Line 1"
            %dd= f.text_field :billing_address3, :placeholder => "Town/City"
            %dd= f.text_field :billing_address4, :placeholder => "County"
            %dd= f.text_field :billing_postcode, :placeholder => "Postcode", :class => 'postcode'
            %dd= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name
            %dd
              = f.check_box :separate_delivery_address
              = f.label :separate_delivery_address, "Deliver to a different address?"
          %dl.delivery
            %dt= f.label :delivery_address1, "Delivery Address", :class => 'req'
            %dd= f.text_field :delivery_name, :placeholder => "Deliver to (name/company)"
            %dd= f.text_field :delivery_address1, :placeholder => "Line 1"
            %dd= f.text_field :delivery_address3, :placeholder => "Town/City"
            %dd= f.text_field :delivery_address4, :placeholder => "County"
            %dd= f.text_field :delivery_postcode, :placeholder => "Postcode", :class => 'postcode'
            %dd= f.collection_select :delivery_country_id, Shoppe::Country.ordered, :id, :name
            
      %p.submit= f.submit "Continue to payment"

  - else
    %p Please call us to place this order. 
    

app/views/orders/confirmation.html.haml
- @page_title = 'Checkout'
= render 'checkout_sidebar'
.checkout
  %h2 Let's do this thing!
  %p.intro
    Brilliant! We have everything we need to place the order. Check the items below carefully,
    and if you're happy click 'Place Order' to submit the order.
  = render 'shared/order_items', :order => current_order, :readonly => true
  = form_tag checkout_confirmation_path, :method => :patch, :class => 'disableable' do
    %p.submit= submit_tag "Place Order", :class => 'order'

app/views/orders/payment.html.haml
- @page_title = 'Checkout'
= render 'orders/checkout_sidebar'

.checkout
  %p.secure Secure connection
  %h3 Pay using your credit/debit card
  = form_for @order, :url => checkout_payment_path, :html => {:class => 'checkout'} do |f|
    = field_set_tag nil, :class => 'payment' do
      %h3 This is a demo form. Any values entered here will be accepted.
      %dl
        %dt= label_tag 'card_number', "Full Card Number"
        %dd.number= text_field_tag 'card_number', '', :name => nil
      %dl
        %dt= label_tag 'exp_month', "Expiry Date (mm/yyyy)"
        %dd.expiry
          = select_tag nil, options_for_select((1..12).to_a)
          = select_tag nil, options_for_select((Date.today.year..Date.today.year + 10).to_a), :class => 'year'
      %dl
        %dt= label_tag 'cvc', "Security Code"
        %dd.cvc
          = text_field_tag 'cvc', '', :name => nil, :maxlength => 4
          %span This is the 3 digit number on the back of your card.
    %p.submit= f.submit "Review your order", :class => 'review'

app/views/orders/show.html.haml
- @page_title = 'Your Shopping Bag'
.checkout
  %h2 Your shopping bag
  %p.intro
    The items listed below are currently in your shopping bag. If you're ready to place your order
    just click the 'Checkout' button on the right and we'll ask for a few details and place the order.

  = render 'shared/order_items', :order => current_order
  

app/views/orders/status.html.haml
- @page_title = "Order Status ##{@order.number} "
.status
  
  .details
    .left
      %dl
        %dt Name
        %dd= @order.first_name + ' ' + @order.last_name
        %dt Company
        %dd= @order.company.blank? ? '-' : @order.company
        %dt Delivery Address
        %dd= @order.delivery_address1
        %dd= @order.delivery_address2
        %dd= @order.delivery_address3
        %dd= @order.delivery_address4
        %dt Postcode
        %dd= @order.delivery_postcode
        %dd= @order.delivery_country.try(:id)
    .right
      %dl
        %dt Order Number
        %dd= @order.number
        %dt E-Mail Address
        %dd= @order.email_address
        %dt Telephone
        %dd= @order.phone_number
        %dt Weight
        %dd #{@order.total_weight}kg
  
  
  .status-bar
    %ul
      - if @order.received?
        %li.received
          %h4 Order Received
          %p on #{@order.received_at.to_s(:long)}

      - if @order.paid?
        %li.payment
          %h4 Payment Received
          %p on #{@order.paid_at.to_s(:long)}

      - if @order.accepted?
        %li.accepted
          %h4 Order Accepted
          %p on #{@order.accepted_at.to_s(:long)}

      - elsif @order.rejected?
        %li.rejected
          %h4 Order rejected
          %p on #{@order.rejected_at.to_s(:long)}

      - if @order.shipped?
        %li.shipped
          %h4 Order Shipped
          %p on #{@order.shipped_at.to_s(:long)}
          - if @order.courier_tracking_url
            %p= link_to "Track the delivery", @order.courier_tracking_url
          - else
            %p Consignment # <b>#{@order.consignment_number}</b>
  
  = render 'shared/order_items', :order => @order, :readonly => true